### ISSUE TITLE
Add a branding logo to center of AppBar in mobile screen.

### ISSUE THREAD

**Issue by anoochit** [anoochit/leap_ota_portal#2]
The web frontend has a responsive UI BUT it need to add a branding logo (now a FlutterLogo widget) to the center of AppBar, see the following image.

<img width="807" alt="image" src="https://github.com/anoochit/leap_ota_portal/assets/1182518/56c926e3-4f11-495c-b244-9d54d94435d2">

<img width="759" alt="image" src="https://github.com/anoochit/leap_ota_portal/assets/1182518/e6789d38-f57e-4cf3-b538-37d584206540">

This change has the following effect:

 - HomeView
 - BrandView

**Comment by vasusomani** [comment]
Hi, I'm not able to navigate to Home Page

**Comment by anoochit** [comment]
> Hi, I'm not able to navigate to Home Page

1. Start a backend server
2. Add test user 

more detail in [README](https://github.com/anoochit/leap_ota_portal/tree/master/server#readme)
