### ISSUE TITLE
Add sign up feature in signup screen

### ISSUE THREAD

**Issue by anoochit** [anoochit/leap_ota_portal#5]
The app already has a sign-up screen but doesn't have an action yet, so you can use the existing signup screen to write a service to connect to the backend to complete this feature.

Backend is already has signup endpoint, just send POST request with a json data below

`POST http://localhost:8080/signup `
`Content-Type: application/json`

```json
{
"name" : "bob",
"username":"bob@example.com",
"password":"password"
}
```

**Comment by Aryashakya** [comment]
Hi, I would like to work on this.

**Comment by anoochit** [comment]
> Hi, I would like to work on this.

Thank you, please fork and PR.

**Comment by Aryashakya** [comment]
#6 Please review it.
